<a href="https://colab.research.google.com/github/aravint-annamalai/PyTorch/blob/main/PyTorch_60_minute_blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# TENSOR INITIALIZATION

## torch.tensor - Directly from data 

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

## torch.from_numpy - From a NumPy array

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

## From another tensor

### torch.ones_like

Tensor of all ones having the same shape as the input tensor 

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



### torch.rand_like

Tensor of random numbers having the same shape as the input tensor

In [6]:
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random tensor: \n {x_rand} \n")

Random tensor: 
 tensor([[0.6605, 0.0591],
        [0.4109, 0.5527]]) 



## With random or constant values

In [7]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")
print(f"Zeros tensor: \n {zeros_tensor} \n")

Random tensor: 
 tensor([[0.9185, 0.6894, 0.0908],
        [0.4378, 0.2312, 0.1753]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# TENSOR ATTRIBUTES

In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Devce tensor is stored on: cpu


In [9]:
assert rand_tensor.shape == rand_tensor.size()