<a href="https://colab.research.google.com/github/aravint-annamalai/PyTorch/blob/main/Tensors_PyTorch_60_minute_blitz.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

# TENSOR INITIALIZATION

## torch.tensor - Directly from data 

In [2]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

In [3]:
x_data

tensor([[1, 2],
        [3, 4]])

## torch.from_numpy - From a NumPy array

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]])

## From another tensor

### torch.ones_like

Tensor of all ones having the same shape as the input tensor 

In [5]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 



### torch.rand_like

Tensor of random numbers having the same shape as the input tensor

In [6]:
x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random tensor: \n {x_rand} \n")

Random tensor: 
 tensor([[0.1098, 0.4555],
        [0.8467, 0.6821]]) 



## With random or constant values

In [7]:
shape = (2,3)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random tensor: \n {rand_tensor} \n")
print(f"Ones tensor: \n {ones_tensor} \n")
print(f"Zeros tensor: \n {zeros_tensor} \n")

Random tensor: 
 tensor([[0.3588, 0.3252, 0.4485],
        [0.1834, 0.8162, 0.7564]]) 

Ones tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



# TENSOR ATTRIBUTES

In [8]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


In [9]:
assert rand_tensor.shape == rand_tensor.size()

# TENSOR OPERATIONS

In [11]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [12]:
tensor.device

device(type='cuda', index=0)

In [13]:
tensor = torch.ones((4,4))
tensor[:,1] = 0
tensor

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

## Joining tensors

The below code concatenates the above tensor thrice, side-by-side

In [14]:
t1 = torch.cat([tensor, tensor, tensor], axis=1)
t1

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])

## Multiplying tensors

The below code shows two different ways of multiplying two tensors element-by-element

In [15]:
print(f"tensor.mul(tensor) \n {tensor.mul(tensor)} \n")
print(f"tensor*tensor \n {tensor*tensor} \n")

tensor.mul(tensor) 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor*tensor 
 tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 



Two ways of matrix multiplication between two tensors

In [16]:
print(f"tensor.matmul(tensor.T) \n {tensor.matmul(tensor.T)} \n")
print(f"tensor @ tensor.T \n {tensor @ tensor.T} \n")

tensor.matmul(tensor.T) 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

tensor @ tensor.T 
 tensor([[3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.],
        [3., 3., 3., 3.]]) 

